[project]
name = "nc-mcp"
version = "0.1.0"
description = "MCP Server for NetCDF format file"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.11.3",
    "netcdf4>=1.7.2",
    "numpy>=2.3.2",
    "pytest>=8.4.1",
]
